import type { WikiArticle } from "../infoContent";

export const article: WikiArticle = {
  id: "digits-and-bases",
  title: "Digits make patterns",
  summary: "Binary digits can build a sequence that is regular, musical, and never repeating.",
  icon: "keypad-outline",
  sections: [
    {
      id: "thue-morse-rule",
      title: "Count the 1s",
      body: [
        "The Thue-Morse sequence writes 0 when a number has an even number of 1s in binary, and 1 when it has an odd number: 0, 1, 1, 0, 1, 0, 0, 1, …. It is built by copying a block and then flipping every bit.",
        "It never settles into a repeating loop, yet it is generated by a tiny machine that only reads binary digits. That makes it an automatic sequence.",
      ],
      anums: ["A010060", "A000069", "A001969"],
    },
    {
      id: "thue-morse-see-hear",
      title: "See it and hear it",
      body: [
        "Use a mod grid or turtle walk. In the grid, the copied-and-flipped blocks make the recursion obvious. With rhythm enabled, the 0s and 1s form a recognizable binary pulse rather than a simple repeated beat.",
      ],
    },
    {
      id: "thue-morse-real-world",
      title: "In the real world",
      body: [
        "Thue-Morse gives a fair-looking way to alternate two choices. Prouhet's construction uses it to split consecutive numbers into two teams whose sums, squares, and higher powers balance exactly over carefully chosen blocks.",
      ],
    },
    {
      id: "thue-morse-open-door",
      title: "An open door",
      body: [
        "Automatic sequences sit between repetition and randomness. They are simple enough to generate from digits, but rich enough to raise hard questions about patterns, frequencies, and what a small machine can create.",
      ],
      links: [
        { label: "Thue-Morse sequence, OEIS A010060", url: "https://oeis.org/A010060" },
        { label: "Allouche and Shallit, Automatic Sequences", url: "https://doi.org/10.1017/CBO9780511546563" },
      ],
    },
  ],
};
