import type { WikiArticle } from "../infoContent";
import { WIKI_IMAGES } from "../wikiImages";

export const article: WikiArticle = {
  id: "seeing",
  title: "Ways to see a sequence",
  summary: "Visualization as a mathematical instrument, from Ulam's doodle to log scales.",
  icon: "eye-outline",
  sections: [
    {
      id: "seeing-instrument",
      body: [
        "A plot is not a decoration on top of mathematics. Used properly, it is an instrument, in the same sense a telescope is: a device that converts something outside our perceptual range into something inside it.",
        "Numbers as symbols pass through the slow, serial machinery of reading. The same numbers as positions, lengths, and angles pour into the visual cortex, which processes spatial pattern massively in parallel and for free. A visualization is a way of borrowing that hardware for arithmetic.",
        "The classic demonstration of what summary numbers hide is Anscombe's quartet: four small datasets constructed in 1973 to share the same means, variances, correlation, and regression line, which nevertheless look wildly different the moment they are plotted, one a clean line, one a curve, one a line with an outlier, one a vertical stack [1]. Francis Anscombe built it to scold statisticians who trusted tables over graphs. The lesson transfers directly to sequences: two sequences can share every headline statistic and have completely different personalities, and the fastest way to meet the personality is to look.",
      ],
      image: {
        ...WIKI_IMAGES.romanesco,
        caption:
          "The eye is a pattern instrument. It finds the spiral-of-spirals structure in a Romanesco head instantly, with no arithmetic; visualization aims that same machinery at numbers.",
      },
    },
    {
      id: "seeing-ulam",
      title: "A doodle at a boring talk",
      body: [
        "The most famous accidental experiment in mathematical visualization happened in 1963. Stanislaw Ulam, the Los Alamos mathematician best known for his work on the hydrogen bomb and the Monte Carlo method, was sitting through what he later described as a long and very boring talk. He started doodling: whole numbers in a square spiral, 1 at the center, winding outward counterclockwise.",
        "Then he circled the primes. What he saw made him sit up. The primes were not scattered evenly; they crowded onto diagonal lines [2].",
        "Ulam did what a good experimentalist does with a suggestive first observation: he scaled it up. With Myron Stein and Mark Wells he put the MANIAC II computer at Los Alamos to work, producing pictures of the spiral out to tens of thousands of numbers, and the diagonal streaks persisted. They published the pictures in 1964 under the deadpan title A Visual Display of Some Properties of the Distribution of Primes [2], and Martin Gardner ran the story in his Scientific American column that March, putting the spiral on the magazine's cover and into the world's imagination [3].",
        "Honesty about priority: the herpetologist Laurence Klauber, a rattlesnake expert who did mathematics on the side, had presented a similar triangular arrangement in 1932, and hardly anyone noticed. It was the picture, mass-printed in 1964, that made the idea unforgettable.",
        "What do the diagonals actually mean? Follow any diagonal in the spiral and compute the numbers on it: they are generated by a quadratic polynomial, of the form $4n^2 + bn + c$. So \"primes cluster on certain diagonals\" is the visual translation of a real arithmetic claim: some quadratic polynomials are unusually rich in primes.",
        "That claim predates the spiral by decades. Euler noticed in 1772 that $n^2 + n + 41$ yields primes for every n from 0 through 39, and the richness of quadratics in primes is precisely the content of Hardy and Littlewood's Conjecture F from 1923, which predicts, for each such polynomial, the exact asymptotic density of primes it should produce [4]. A century later, Conjecture F remains unproven; it is not even known that any single quadratic polynomial produces infinitely many primes.",
        "The spiral did not solve any of this. What it did was make an invisible open problem visible, and that is the whole job description of a mathematical instrument.",
        "You can rerun Ulam's experiment yourself in about a minute. Open the primes in this app, switch to the Ulam spiral view, and let your eye adjust. First you will see the obvious: no primes on the even diagonals, since half the grid is even numbers.",
        "Then the streaks emerge, some diagonals dense with primes, others nearly barren, and you will feel the same pull Ulam felt: the certainty that there is a reason. There is, and it is called Conjecture F, and nobody has proved it. You are looking at an open problem with your bare eyes.",
      ],
      figure: {
        kind: "ulam-mini",
        params: { highlightDiagonal: true },
        caption:
          "The first 400 numbers in Ulam's spiral, primes filled: notice how the squares chain along diagonals, the pattern that made Ulam sit up in 1963.",
      },
      anums: ["A000040", "A005846"],
      quote: {
        text: "The purpose of computing is insight, not numbers.",
        attribution: "Richard Hamming, Numerical Methods for Scientists and Engineers, 1962",
      },
    },
    {
      id: "seeing-arcs",
      title: "Recamán's arcs: geometry from a walk",
      body: [
        "Recamán's sequence jumps along the number line, back when it can, forward when it must. Print its terms and you get fog: 0, 1, 3, 6, 2, 7, 13, 20, 12, 21, 11. The visualization that dissolved the fog draws each jump as a semicircle spanning its start and end on the number line, alternating above and below the line, a rendering worked out by the mathematical artist Edmund Harriss and spread by a 2018 Numberphile video [5]. This app's Recamán arc view draws the same picture live.",
        "Notice what the arcs encode and what they discard. Time is gone: you cannot easily tell the fifth jump from the fiftieth. In exchange, the geometry exposes exactly the things the number list hides: nested arcs show the sequence doubling back through territory it skipped, near-tangent arcs show close revisits, and the slow drift of the whole structure rightward shows the average escape to larger numbers. The open coverage question, does every number get visited, becomes visible as the gaps the arcs keep leaping over.",
        "Every visualization makes this same trade: it spends some dimensions of the data to buy salience for others. The arcs spend time to buy structure.",
        "The Recamán view rewards a second kind of looking: comparison across scales. Watch the first fifty terms and the walk seems almost polite, filling in the small numbers it skipped. Let it run to a few hundred and the character changes, with long forward marches and increasingly desperate returns.",
        "That shift is real, and it is the visual counterpart of the statistics behind the open question from the mysteries article: the sequence spends more and more of its time far from the territory it has left unfinished. A table of terms contains this fact; the picture confronts you with it.",
      ],
      anums: ["A005132"],
    },
    {
      id: "seeing-log",
      title: "Why log scales exist",
      body: [
        "Try plotting Fibonacci on ordinary axes: within forty terms the curve is a vertical wall, and every detail of how it grew is crushed into the floor. This is not a Fibonacci problem; it is what exponential growth does to linear axes. The repair is the logarithmic scale, which spaces values by their ratios instead of their differences, so that 10, 100, and 1000 sit evenly apart. On a log scale, multiplication becomes a fixed step upward, and exponential growth, which multiplies by a constant each term, becomes a straight line.",
        "That straightening is diagnostic, not cosmetic. If a sequence is a straight line on a log scale, it grows exponentially, and the slope tells you the base. If two sequences run parallel, they share a growth base and differ by a constant factor. If the curve bends upward even on a log scale, growth is faster than exponential (the factorials do this); bending down means subexponential.",
        "A power law like $n^2$ is curved on a log scale but straightens on log-log axes, where both coordinates are logarithmic. Reading curvature on log axes is a skill worth deliberately practicing, and it is the reason this app's Compare view overlays sequences on a shared log scale: comparing raw exponentials on linear axes tells you nothing but who is bigger at the edge of the chart.",
      ],
      figure: {
        kind: "term-plot",
        params: {
          terms: [
            1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597,
            2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418,
            317811, 514229, 832040,
          ],
          label: "Fibonacci, 30 terms",
        },
        caption:
          "Thirty Fibonacci numbers on the log scale this figure uses: exponential growth reads as a near-straight line, where linear axes would crush the first twenty terms into the floor.",
      },
      anums: ["A000045", "A000142"],
    },
    {
      id: "seeing-compare",
      title: "Two sequences at once",
      body: [
        "With exactly two sequences, the compare screen adds two more instruments. The ratio view plots term-by-term quotients: a flat ratio line means one sequence is a constant multiple or shift of the other. The phase plane plots one sequence against the other, discarding n entirely; complementary pairs, two lists that together hit every whole number exactly once, hug the diagonal there. The \"Classic matchups\" presets are curated examples of each behavior.",
      ],
      figure: {
        kind: "ratio-convergence",
        params: { count: 12 },
        caption:
          "The ratio view in miniature: successive Fibonacci quotients F(n+1)/F(n) settle onto the dashed golden ratio line within a dozen terms.",
      },
    },
    {
      id: "seeing-families",
      title: "The app's visualization families",
      body: [
        "A handful of sequences in this app have dedicated views, each an instrument tuned to that sequence's own structure: Recamán arcs, the Fibonacci golden spiral, the Ulam spiral for primes, the Collatz trajectory tree, the Pascal-triangle parity fractal, and digit flow for constants like $\\pi$.",
        "Everything else gets a generic visualization chosen from the shape of its terms, and each choice answers a different question. The line plot answers \"how does it grow?\" and is the default for monotone growth. The signed bar waveform answers \"how does it oscillate?\" and suits sequences that cross zero. The turtle walk turns terms into turning angles and answers \"is there hidden periodicity or drift?\", since periodic sequences draw closed shapes and aperiodic ones wander.",
        "The polar spiral wraps the sequence around the golden angle and exposes modular structure as spiral arms. The mod-2 grid keeps only parity and answers \"what is the rhythm of odd and even?\", which is where self-similar structure like Pascal's often pops out. The chips at the top right of any visualization switch between these views, and the help chip explains what the active one encodes.",
        "The point of having a family rather than one canonical picture: there is no such thing as what a sequence looks like. There is only what a sequence looks like under a chosen encoding, and switching encodings is the visual equivalent of asking a different question.",
      ],
    },
    {
      id: "seeing-bias",
      title: "What the picture hides",
      body: [
        "Now the honest section. Every visualization in this app, and everywhere else, is a lossy compression. A sequence is an infinite object; a screen has a few million pixels; something has to be thrown away, and the designer, not the mathematics, chooses what.",
        "The mod-2 grid discards everything about a term except one bit. The log scale that straightens exponentials also flattens the additive detail: on log axes, the difference between 1,000,000 and 1,000,100 is invisible. The turtle walk's shape changes completely if you map terms to angles differently. None of these pictures is the sequence; each is one deliberately chosen shadow of it, and this article's companion thesis, that every representation is a compression and every compression is an editorial act, applies to every view in this app without exception.",
        "Perception adds its own biases on top. Cleveland and McGill measured in 1984 which visual encodings humans read accurately: judging positions along a common scale is nearly lossless, judging angles and areas is poor, and judging color intensity is worse [6], which is why the app leans on position-based plots and treats color as a label rather than a measurement.",
        "Aspect ratio silently changes the story a curve tells, since the same data reads as flat or dramatic depending on how the axes are stretched. And the eye is an overeager line detector: it will assemble stray points into streaks given the slightest excuse. Some of the drama of the Ulam spiral is real arithmetic, but some is the human visual system doing what it always does to a grid of dots.",
        "So treat every picture the way a scientist treats an instrument reading. A visualization can surface a conjecture, kill a conjecture, or point at the right question; the Ulam spiral did all three. What it cannot do is prove anything, and the moment a picture convinces you of something, the correct next move is to change the encoding and see whether the conviction survives. In this app that costs one tap.",
      ],
    },
    {
      id: "seeing-glossary",
      title: "Tags and difficulty",
      body: [
        "Sequences in the app carry small tags so you can tell at a glance what area of math they touch and how approachable they are. Difficulty measures how easy the rule is to understand, not how hard the open problems are; as the Learn articles show, those two scales are close to independent.",
      ],
      bullets: [
        "Beginner: you can follow this with basic counting.",
        "Intermediate: some math vocabulary helps, but the viz carries you.",
        "Advanced: easy to state, deeply subtle to grasp.",
        "Number theory: primes, divisors, and the hidden structure of whole numbers.",
        "Combinatorics: counting arrangements. How many ways can things combine?",
        "Geometry: shapes, spirals, and where numbers land in space.",
        "Analysis: constants like π and e, limits, and digit expansions.",
        "Algebra: polynomials, coefficients, and symbolic structure.",
        "Probability: randomness, expected values, and statistical patterns.",
        "Recreational: puzzles and playful rules, math for the fun of it.",
        "Fractals: self-similar patterns that repeat at every scale.",
      ],
    },
  ],
  citations: [
    "F. J. Anscombe, Graphs in statistical analysis, The American Statistician 27 (1973), 17-21.",
    "M. L. Stein, S. M. Ulam, and M. B. Wells, A visual display of some properties of the distribution of primes, American Mathematical Monthly 71 (1964), 516-520.",
    "M. Gardner, Mathematical games: The remarkable lore of the prime numbers, Scientific American 210 (March 1964), 120-128.",
    "G. H. Hardy and J. E. Littlewood, Some problems of 'Partitio Numerorum' III: On the expression of a number as a sum of primes, Acta Mathematica 44 (1923), 1-70.",
    "A. Bellos and B. Haran, The Slightly Spooky Recamán Sequence, Numberphile video, 2018; spiral drawing by E. Harriss.",
    "W. S. Cleveland and R. McGill, Graphical perception: Theory, experimentation, and application to the development of graphical methods, Journal of the American Statistical Association 79 (1984), 531-554.",
  ],
};
